apiVersion: v1
kind: ConfigMap
metadata:
  name: app-secrets
data:
  SECRET_KEY: "k8s-secret-key"
  DEBUG: "False"
  DATABASE_URL: "postgres://user:password@db-host:5432/enterprise_db"
  REDIS_URL: "redis://redis-host:6379/0"
